name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '!charts/**/README.md'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.2

      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_repo_url: https://jevy.github.io/blakeshome-charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
